bankproject/bankapp/urls.py
from django.urls import path,include

from . import views
app_name='bankapp'

urlpatterns = [
    path('',views.home,name='home'),
     path('login/',views.login,name='login'),
    path('logout/', views.logout, name='logout'),
    # path('signup/',views.signup,name='signup'),
    path('reg/',views.register,name='register'),
    path('reg/register',views.login,name='login'),

     path('detail/',views.detail,name='detail'),
    path('regform/',views.registerform,name='registerform'),
    path('/form',views.form,name='form'),
    path('submit/',views.submit,name='submit'),
    path('/branch',views.branch,name='branch'),
]

bankproject/bankproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankproject/bankapp/models.py
from django.db import models

# Create your models here.
class Branches(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

bankproject/bankapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
from .models import Branches


def home(request):
    return render(request,"home.html")

def logout(request):
    auth.logout(request)
    return redirect('/')
def login(request):
    if request.method=='POST':
        Username=request.POST['Username']
        Password=request.POST['Password']
        user=auth.authenticate(Username=Username,Password=Password)
        if user is not None:
            auth.login(request,user)
            return redirect('/')
        # else:
        #      messages.info(request,"invalid credentials")
        #     messages.info(request,"successfull login")
    return render(request,"login.html")
def register(request):
    if request.method == 'POST':
        Username = request.POST['Username']
        Firstname = request.POST['Firstname']
        Lastname = request.POST['Lastname']
        email= request.POST['email']
        Password = request.POST['Password']
        Password1 = request.POST['Password1']
        if Password == Password1:
            if User.objects.filter(Username=Username).exists():
                messages.info(request,"Username taken")
                return redirect('register')
            elif User.objects.filter(email=email).exists():
                messages.info(request,"email already exists")
                return redirect('register')
            else:
               user = User.objects.create_user(Username=Username, Password=Password, Firstname=Firstname,
                                            Lastname=Lastname, email=email)
               user.save()
               return redirect('login')
              # print("User Created")
        else:
            messages.info(request,"password not matching")
            return redirect('register')
         # return redirect('/')
    return render(request, "register.html")
def detail(request):
    return  render(request,'detail.html')
def registerform(request):
    return render(request,'registerform.html')
def form(request):
    return render(request,'form.html')
def logout(request):
    auth.logout(request)
    return redirect('/')
def submit(request):

        return render(request,'submit.html')
def branch(request):
    b=Branches.objects.all()
    context={
        'b':b
    }
    return render(request,"index.html",context)

bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">
     <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block tittle %}{% endblock %}</title>

</head>

<body class="d-flex flex-column min-vh-100">
<div class="container">

{% include 'header.html' %}
{% include 'navbar.html' %}
    {% block content %}
{% endblock %}
{% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</div>
</body>
</html>

bankproject/templates/detail.html
{{b.name}}

bankproject/templates/footer.html
<center>
    <footer class="mt-auto" >
<div class="footer navbar-fixed-bottom my_footer" style="width:1290px; height:50px; background-color:#f8f9fa;
        padding-top:20px;
         font-size:14px;">

        <p class="text-center">&copy;ALL RIGHTS ARE RESERVED</p>

</div>
    </footer>
    </center>

bankproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Form</title>
</head>
<body>
<div>
<h2>Form Requirements</h2>
<input type="text" name="name" placeholder="Name"><br>
<input type="date" name="dob" placeholder="DOB"><br>
<label>Gender :</label>
<label style="padding:15px">Female</label>
<input type="radio" name="gender">
<label>Male</label>
<input type="radio" name="gender"><br>


<input type="number" name="number" placeholder="Phone no"><br>
<input type="email" name="email" placeholder="Email Id"><br>
<input type="text" name="address" placeholder="Address"><br>
<input type="text" list="district" placeholder="District">
<datalist id="district">
  <option value="Alappuzha">
    <option value="Ernakulam">
  <option value="Kottayam">
  <option value="Kollam">
    <option value="Trivandram">

  <!-- ... -->
</datalist><br>

    <input type="text" list="branches" placeholder="Branches">
    <datalist id="branches">
        <select id="Alappuzha">

        <option value="Ambalapuzha">
    <option value="Kayamkulam">
            <option value="Kottarakara">
    <option value="Aluva">
            <option value="Chengannur">
    <option value="Pandalam">

            </select>
        </datalist><br>

<!--        <select id="Alappuzha">-->
<!--        <option value="Ambalapuzha">-->
<!--    <option value="Kayamkulam">-->
<!--            </select>-->
<!--        <br>-->

<input type="text" list="account" placeholder="Account Type">
<datalist id="account">
  <option value="Current">
    <option value="Savings">
  <option value="Fixed">


  <!-- ... -->
</datalist><br>

<label>Materials Provided : </label>

  <label>Credit Card</label>
<input type="checkbox">
<label>Debit Card</label>
<input type="checkbox"><br>
<!--<input type="submit"><br>-->
  <form method="POST" action="submit/">
    {% csrf_token %}
       <input type="submit">
     </form>


<a class="btn btn-secondary" href="{% url 'bankapp:logout' %}">Logout</a>

</div>
</body>
</html>

bankproject/templates/header.html
{% load static %}
<header>
    <center>
        <a href=""><img src="{% static 'img/imglogo.png' %}" alt="logimage" width="100px" height="100px"></a>
    </center>
</header>

bankproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" alt=""  width="1295px;" height="550px">
</div>
<div>
 <p class="text-justify"><h2><b>REASONS TO BANK WITH US</b></h2><br>
     Accessing your savings account is easy and convenient with our wide network of 1300+ branches and 24x7 ATMs across the country. Your savings account is always at your fingertips with our best in class net banking feature, SMS banking and our award winning mobile banking app for all your online transactions.<br><b>FIND A SAVINGS ACCOUNT THAT SUITS YOUR NEEDS</b><br>
Apart from regular features and offers like cashbacks and discounts, Kotak Bank have also come up with special savings account programmes designed specifically for women, children, senior citizens, working professionals and for the entire family. Please provide us with a few details related to your requirements so that we can find the most suitable savings account to meet your banking needs. </p>
</div>
<br>
<div class="team">
		<div class="container">
			<div class="row">
				<div class>
<!--					<div class="section_subtitle">simply amazing places</div>-->
					<h2><b>Managing Directors</b></h2>
				</div>
			</div>
			<div class="row team_row">

				<!-- Team Item -->


				<div class="col-xl-3 col-md-6 team_col">
					<div class="team_item d-flex flex-column align-items-center justify-content-start text-center">
						<div class="team_image"><img src="{% static 'img/md1.jpg' %}" alt="" style="width:200px;height:200px;"></div>
						<div class="team_content">
							<div class="team_title">Mr.Radhakrishnan</div>
							<div class="team_text">

							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-3 col-md-6 team_col">
					<div class="team_item d-flex flex-column align-items-center justify-content-start text-center">
						<div class="team_image"><img src="{% static 'img/md2.jpg' %}" alt=""  style="width:200px;height:200px;"></div>
						<div class="team_content">
							<div class="team_title">James Williams</div>
							<div class="team_text">
<!--								<p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.</p>&ndash;&gt;-->
							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-3 col-md-6 team_col">
					<div class="team_item d-flex flex-column align-items-center justify-content-start text-center">
						<div class="team_image"><img src="{% static 'img/md3.jpg' %}" alt=""  style="width:200px;height:200px;"></div>
						<div class="team_content">
							<div class="team_title">Mr.HariNarayan</div>
							<div class="team_text">
<!--								<p>Pellentesque sit amet elementum ccumsan sit amet mattis eget, tristique at leo. Vivamus massa.</p>&ndash;&gt;-->
							</div>
						</div>
					</div>
				</div>


<!--&lt;!&ndash; Footer Contact Item &ndash;&gt;-->
<!--						<div class="container">-->
<!--                        <div class="col-xl-4 footer_contact_col">-->
<!--							<div class="footer_contact_item d-flex flex-column align-items-center justify-content-start text-center">-->
<!--&lt;!&ndash;								<div class="footer_contact_icon"><img src="{% static 'img/contactimg.jpg' %}" alt="" width="1295px;" height="550px;"></div>&ndash;&gt;-->
<!--								<div class="footer_contact_title" style="text-right">Contact Us</div>-->
<!--								<div class="footer_contact_list">-->
<!--									<ul>-->
<!--										<li>janatabank@gmail.com</li>-->
<!--										<li>janatabankoffical.com</li>-->
<!--									</ul>-->
<!--								</div>-->
<!--							</div>-->
<!--						</div>-->
<!--                        </div>-->

					</div>
    {% endblock %}

bankproject/templates/index.html
{% for i in context %}
{{i.name}}
{% endfor %}

bankproject/templates/login.html
{% load static %}
<form method="POST">
     {% csrf_token %}
    <h2>Login To Continue</h2><br>
    <input type="text" name="Username" placeholder="Enter Username"><br>

    <input type="text" name="Password" placeholder="Enter password"><br>
    <input type="text" name="Password1" placeholder="Conform password"><br>
    <input type="submit"><br>
     <a class="btn btn-warning" href="{% url 'bankapp:registerform' %}">Register</a>


</form>

bankproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'bankapp:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bankapp:register' %}">Register</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Branches
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha ">Alapuzzha</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Trivandram">Trivandram</a></li>
            <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta">Pathanamthitta</a></li>

          </ul>
        </li>

    </div>
  </div>
  <a class="btn btn-secondary" href="{% url 'bankapp:register' %}">User</a>
</nav>

bankproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<body>
<form action="register" method="POST">

     {% csrf_token %}
    <h2>Register Page</h2><br>
    <input type="text" name="Username" placeholder="Enter Username"><br>
    <input type="text" name="Firstname" placeholder="Enter your Firstname"><br>
    <input type="text" name="Lastname" placeholder="Enter your Lastname"><br>
    <input type="email" name="email" placeholder="Enter your mail id"><br>
    <input type="text" name="Password" placeholder="Enter password"><br>
    <input type="text" name="Password1" placeholder="Conform password"><br>
    <input type="submit"><br>
    </form>
{% for msg in messages %}
{{msg}}
{% endfor %}
</body>
</html>

bankproject/templates/registerform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img class="my_image my_image_padding" src="{% static 'img/policies.png' %}" alt=""  width="1295px;" height="750px">
</div>
<h2>Registration Form</h2>
<p>Insurance is generally defined as a contract which is also called a policy. An insurance policy is a contract in which an individual or an organization gets financial protection and compensation for any damages by the insurer of the insurance company. In simpler words, one can answer what is an insurance policy as a form of protection from any unexpected loss or damage. From this paragraph, one can get a clear overview of insurance meaning.
<br>
    TO CONTINUE
 </p>
<a class="btn btn-warning" href="{% url 'bankapp:form' %}">CLICK HERE</a>
<div></div>
{% endblock %}

bankproject/templates/signup.html
<form method="POST">
    {% csrf_token %}
    <h2>Login To Continue</h2><br>

    <input type="text" name="Username" placeholder="Username"><br>
    <input type="text" name="Firstname" placeholder="Enter your Firstname"><br>
    <input type="text" name="Lastname" placeholder="Enter your Lastname"><br>
    <input type="email" name="email" placeholder="Enter your mail id"><br>
    <input type="text" name="Password" placeholder="Password"><br>
    <input type="text" name="Password1" placeholder="Conform Password"><br>
    <input type="submit">
</form>

bankproject/templates/submit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div>
    <img class="my_image my_image_padding" src="{% static 'img/success.png' %}" alt=""  width="1295px;" height="550px">
</div>
<h3>Your Registration is Successfully Completed.</h3>

<a class="btn btn-warning" href="{% url 'bankapp:home' %}">Return Home Page</a>
{% endblock %}